### ISSUE TITLE
Adicionar demonstrações visuais da extensão ao README

### ISSUE THREAD

**Issue by oviniciusfeitosa** [moisesrlima/elsePonto#1]
Olá! Primeiramente, parabéns pela excelente iniciativa com esta extensão para Chrome. A proposta é incrível e tem potencial para ajudar muitas pessoas.

Para tornar o repositório ainda mais atrativo e facilitar o entendimento dos novos usuários, gostaria de sugerir a inclusão de demonstrações visuais no `README.md`. Isso pode ser feito através de prints ou, idealmente, um vídeo curto que mostre a extensão em funcionamento.

Essas adições ajudariam os usuários a entenderem melhor o fluxo de uso da extensão e destacariam seus diferenciais de maneira clara.

Continue com esse tipo de trabalho, que você vai longe! 🚀

**Comment by moisesrlima** [comment]
Resolvido
